repositories.remote << 'http://www.ibiblio.org/maven2/'

define 'integration_testing', :version=>"1.0" do
  # TODO integration testing example
  define 'client' do
    package(:jar)
  end
  define 'server' do
    test.with project('client')
    package(:jar)
  end
end