repositories.remote << "http://www.ibiblio.org/maven2/"
repositories.release_to = "file:///~/.m2/repository/"

define "install_upload", :version=>"1.0.0" do
  url = 'http://github.com/phoet/buildr-examples/raw/master/artifacts/install_upload/app.zip'
  app_zip = download('target/app.zip'=>url)
  bean_jar = file('target/app/bean.jar'=>unzip('target/app'=>app_zip))
  bean = artifact('example.com:beans:jar:1.0').from(bean_jar)
  compile.with bean
  install bean
  upload bean
  
  desc 'task for installing an artifact'
  task 'install_directly' do 
    install(bean).invoke
  end
end
