repositories.remote << 'http://www.ibiblio.org/maven2/'

define 'failing', :version=>"1.0" do
  package(:jar)
  test.using :junit
  test.using :fail_on_failure=>false
  test do |test|
    # extension of test task will only get called after a successful test-run
    raise "#{test.failed_tests.size} tests failed"
  end
end
